# Generated by Django 4.0.4 on 2022-11-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_purchase_bill_type_purchase_gstin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=250)),
                ('article_no', models.IntegerField(default=0, null=True)),
                ('size', models.CharField(max_length=50)),
                ('qty', models.IntegerField(null=True)),
                ('free', models.FloatField(default=0.0, null=True)),
                ('p_price', models.FloatField(null=True)),
                ('mrp', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('disc1', models.FloatField(default=0.0, null=True)),
                ('d_Amt1', models.FloatField(default=0.0, null=True)),
                ('disc2', models.FloatField(default=0.0, null=True)),
                ('d_Amt2', models.FloatField(default=0.0, null=True)),
                ('l_Cost', models.FloatField(null=True)),
                ('tot_Cost', models.FloatField(null=True)),
                ('s_Price', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('marg', models.FloatField(null=True)),
                ('pur_bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchase')),
            ],
        ),
    ]
