# Generated by Django 4.0.4 on 2022-12-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_cess_product_gst_product_hsn_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='cess',
            field=models.FloatField(null=True),
        ),
    ]
